spring.application.name=BloomsCafe

# Database - Primary (writes)
primary.datasource.jdbc-url=jdbc:postgresql://localhost:5432/bakery_db
primary.datasource.username=root1
primary.datasource.password=
primary.datasource.driver-class-name=org.postgresql.Driver

# Database - Replica (reads)
replica.datasource.jdbc-url=jdbc:postgresql://localhost:5433/bakery_db
replica.datasource.username=root1
replica.datasource.password=
replica.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# SQL Logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=2000ms
spring.cache.redis.time-to-live=10m
spring.cache.redis.cache-null-values=false

# Jackson
spring.jackson.serialization.fail-on-empty-beans=false

# Actuator / Prometheus
management.endpoints.web.exposure.include=health,metrics,prometheus
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true

# JWT
# jwt.secret=