spring.application.name=BloomsCafe

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/bakery_db
spring.datasource.username=root1
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

# SQL Logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# Jackson
spring.jackson.serialization.fail-on-empty-beans=false

# JWT
# jwt.secret=