spring.application.name=BloomsCafe

# 1. Database Connection Settings
spring.datasource.url=jdbc:postgresql://localhost:5432/bakery_db
spring.datasource.username=root1
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. Hibernate / JPA Engine Configuration
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 3. Schema Strategy Management
spring.jpa.hibernate.ddl-auto=update