upstream bloomscafe_backend {
    server 127.0.0.1:8081;
    server 127.0.0.1:8082;
    server 127.0.0.1:8083;
}

server {
    listen 8080;
    server_name localhost;

    location / {
        proxy_pass http://bloomscafe_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        add_header X-Upstream $upstream_addr;
    }
}
